# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w0GrA0zlnUX1fz-7MT1IUdpsXKSgcAqY
"""

# Commented out IPython magic to ensure Python compatibility.
print("hello world")
!git clone https://github.com/arshscapital/scrape_viz.git
# %cd scrape_viz
print("repo loads ✅")

import pandas as pd, requests, bs4

url = "https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(nominal)"
html = requests.get(url).text
soup = bs4.BeautifulSoup(html, "html.parser")
table = soup.find("table", {"class": "wikitable"})
df = pd.read_html(str(table))[0].head(5)   # first 5 rows
df
df.to_csv("gdp_top5.csv", index=False)
print("saved ✅")

!git add gdp_top5.csv gdp_bar.png
!git commit -m "scrape GDP top-5 + chart"
!git push
!git config --global user.name  "https://github.com/arshscapital"
!git config --global user.email "[apbuttar01@gmail.com]"